version: '3.9'
services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prisma
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
